/**
 * IRM Command - Seed Data
 * Realistic G-SIB bank data for Integrated Risk Management Platform
 * All data is fictional but reflects typical large US bank scenarios
 */

import {
  Risk,
  Control,
  Vendor,
  Issue,
  LossEvent,
  KRI,
  RegulatoryChange,
  RiskScenario,
  AuditEntry,
  MonitoringAlert,
} from './types';

// ============================================================================
// RISKS - 15+ risks across all categories
// ============================================================================

export const risks: Risk[] = [
  {
    id: 'RSK-001',
    title: 'Wholesale Credit Concentration – CRE Portfolio',
    category: 'Credit',
    description:
      'Concentration risk in commercial real estate lending, particularly office and hospitality segments post-COVID market correction. Portfolio exceeds diversification thresholds.',
    businessUnit: 'Commercial Banking',
    impact: 5,
    likelihood: 3,
    inherentScore: 15,
    residualScore: 9,
    owner: 'john.chen@bank.com',
    status: 'Active',
    controlIds: ['CTL-001', 'CTL-002'],
    kpiIds: ['KRI-001', 'KRI-002'],
    lastAssessmentDate: new Date('2026-02-15'),
    nextReviewDate: new Date('2026-05-15'),
    createdAt: new Date('2025-06-01'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'RSK-002',
    title: 'LIBOR/SOFR Transition Residual Basis Risk',
    category: 'Market',
    description:
      'Basis risk from imperfect LIBOR-SOFR spread relationships in legacy contracts. Customer migration lag and fallback language ambiguity.',
    businessUnit: 'Global Markets',
    impact: 4,
    likelihood: 2,
    inherentScore: 8,
    residualScore: 4,
    owner: 'sarah.martinez@bank.com',
    status: 'Mitigated',
    controlIds: ['CTL-003', 'CTL-004', 'CTL-005'],
    kpiIds: ['KRI-003'],
    lastAssessmentDate: new Date('2026-01-30'),
    nextReviewDate: new Date('2026-07-30'),
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2026-01-30'),
  },
  {
    id: 'RSK-003',
    title: 'BSA/AML Transaction Monitoring Model Risk',
    category: 'Compliance',
    description:
      'Model effectiveness degradation in transaction monitoring system. High false positive rate creating alert fatigue. Potential SAR reporting gaps.',
    businessUnit: 'Compliance',
    impact: 5,
    likelihood: 4,
    inherentScore: 20,
    residualScore: 12,
    owner: 'michael.thompson@bank.com',
    status: 'Active',
    controlIds: ['CTL-006', 'CTL-007', 'CTL-008'],
    kpiIds: ['KRI-004', 'KRI-005'],
    lastAssessmentDate: new Date('2026-02-01'),
    nextReviewDate: new Date('2026-08-01'),
    createdAt: new Date('2025-03-20'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'RSK-004',
    title: 'Cloud Infrastructure Single-Provider Dependency',
    category: 'ThirdParty',
    description:
      'Over-reliance on single cloud provider (AWS) for critical systems. Concentration of operational resilience risk. Vendor lock-in limiting switching options.',
    businessUnit: 'Technology',
    impact: 5,
    likelihood: 2,
    inherentScore: 10,
    residualScore: 6,
    owner: 'lisa.park@bank.com',
    status: 'Under Review',
    controlIds: ['CTL-009', 'CTL-010'],
    kpiIds: ['KRI-006'],
    lastAssessmentDate: new Date('2026-01-20'),
    nextReviewDate: new Date('2026-06-20'),
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'RSK-005',
    title: 'Cross-Border Data Transfer – EU/UK GDPR',
    category: 'Compliance',
    description:
      'Adequacy decision framework for cross-border data transfers to UK post-Brexit. SCCs and BCRs complexity. Regulatory enforcement risk.',
    businessUnit: 'Risk Management',
    impact: 4,
    likelihood: 2,
    inherentScore: 8,
    residualScore: 4,
    owner: 'emma.johnson@bank.com',
    status: 'Active',
    controlIds: ['CTL-011', 'CTL-012'],
    kpiIds: ['KRI-007'],
    lastAssessmentDate: new Date('2025-12-15'),
    nextReviewDate: new Date('2026-06-15'),
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date('2025-12-15'),
  },
  {
    id: 'RSK-006',
    title: 'Core Banking Platform EOL Migration',
    category: 'Operational',
    description:
      'Legacy core banking system end-of-life requiring platform migration. 3-year timeline with execution risk, cost overrun potential, and service continuity concerns.',
    businessUnit: 'Operations',
    impact: 5,
    likelihood: 3,
    inherentScore: 15,
    residualScore: 9,
    owner: 'robert.kumar@bank.com',
    status: 'Active',
    controlIds: ['CTL-013', 'CTL-014', 'CTL-015'],
    kpiIds: ['KRI-008'],
    lastAssessmentDate: new Date('2026-02-10'),
    nextReviewDate: new Date('2026-08-10'),
    createdAt: new Date('2025-02-20'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'RSK-007',
    title: 'Payments Processing Vendor Concentration',
    category: 'ThirdParty',
    description:
      '85% of daily payment volume routed through single vendor. Single point of failure for customer transaction processing.',
    businessUnit: 'Operations',
    impact: 5,
    likelihood: 1,
    inherentScore: 5,
    residualScore: 3,
    owner: 'james.wilson@bank.com',
    status: 'Mitigated',
    controlIds: ['CTL-016', 'CTL-017'],
    kpiIds: ['KRI-009'],
    lastAssessmentDate: new Date('2026-01-15'),
    nextReviewDate: new Date('2026-07-15'),
    createdAt: new Date('2024-11-05'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'RSK-008',
    title: 'Interest Rate Risk in Banking Book (IRRBB)',
    category: 'Market',
    description:
      'Economic value of equity sensitivity to rate movements. Deposit beta assumptions under stress. Mismatch in deposit repricing dynamics.',
    businessUnit: 'Treasury',
    impact: 4,
    likelihood: 3,
    inherentScore: 12,
    residualScore: 7,
    owner: 'david.lopez@bank.com',
    status: 'Active',
    controlIds: ['CTL-018', 'CTL-019', 'CTL-020'],
    kpiIds: ['KRI-010'],
    lastAssessmentDate: new Date('2026-02-20'),
    nextReviewDate: new Date('2026-08-20'),
    createdAt: new Date('2025-04-12'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'RSK-009',
    title: 'Cybersecurity – Ransomware Attack Vector',
    category: 'Cyber',
    description:
      'Evolving ransomware threats targeting financial services. Supply chain compromise risk. Endpoint and network attack surface.',
    businessUnit: 'Technology',
    impact: 5,
    likelihood: 4,
    inherentScore: 20,
    residualScore: 12,
    owner: 'catherine.davis@bank.com',
    status: 'Active',
    controlIds: ['CTL-021', 'CTL-022', 'CTL-023', 'CTL-024'],
    kpiIds: ['KRI-011'],
    lastAssessmentDate: new Date('2026-02-25'),
    nextReviewDate: new Date('2026-05-25'),
    createdAt: new Date('2025-07-01'),
    updatedAt: new Date('2026-02-25'),
  },
  {
    id: 'RSK-010',
    title: 'Model Risk – CECL/ACL Estimation',
    category: 'Credit',
    description:
      'Model validation governance for expected credit loss estimation. Forward-looking information integration. Macro scenario selection.',
    businessUnit: 'Risk Management',
    impact: 4,
    likelihood: 3,
    inherentScore: 12,
    residualScore: 6,
    owner: 'alice.brown@bank.com',
    status: 'Active',
    controlIds: ['CTL-025', 'CTL-026'],
    kpiIds: ['KRI-012'],
    lastAssessmentDate: new Date('2026-01-25'),
    nextReviewDate: new Date('2026-07-25'),
    createdAt: new Date('2025-08-15'),
    updatedAt: new Date('2026-01-25'),
  },
  {
    id: 'RSK-011',
    title: 'Operational Resilience – Critical Service Disruption',
    category: 'Operational',
    description:
      'Business continuity gaps in critical banking services. Recovery time objective (RTO) and recovery point objective (RPO) gaps.',
    businessUnit: 'Operations',
    impact: 5,
    likelihood: 2,
    inherentScore: 10,
    residualScore: 5,
    owner: 'marcus.anderson@bank.com',
    status: 'Under Review',
    controlIds: ['CTL-027', 'CTL-028', 'CTL-029'],
    kpiIds: ['KRI-013'],
    lastAssessmentDate: new Date('2026-02-05'),
    nextReviewDate: new Date('2026-08-05'),
    createdAt: new Date('2025-09-20'),
    updatedAt: new Date('2026-02-05'),
  },
  {
    id: 'RSK-012',
    title: 'Regulatory Capital Calculation – SA-CCR Implementation',
    category: 'Compliance',
    description:
      'Derivative counterparty credit risk calculation complexity. SA-CCR vs. CEM methodology transition. System implementation gaps.',
    businessUnit: 'Global Markets',
    impact: 4,
    likelihood: 2,
    inherentScore: 8,
    residualScore: 4,
    owner: 'patricia.garcia@bank.com',
    status: 'Active',
    controlIds: ['CTL-030', 'CTL-031'],
    kpiIds: ['KRI-014'],
    lastAssessmentDate: new Date('2026-01-30'),
    nextReviewDate: new Date('2026-07-30'),
    createdAt: new Date('2025-10-10'),
    updatedAt: new Date('2026-01-30'),
  },
  {
    id: 'RSK-013',
    title: 'Consumer Compliance – Fair Lending',
    category: 'Compliance',
    description:
      'Fair lending risk in mortgage and auto lending underwriting. Disparate impact analysis and monitoring. Pricing transparency.',
    businessUnit: 'Retail Banking',
    impact: 4,
    likelihood: 2,
    inherentScore: 8,
    residualScore: 4,
    owner: 'stephanie.harris@bank.com',
    status: 'Active',
    controlIds: ['CTL-032', 'CTL-033'],
    kpiIds: ['KRI-015'],
    lastAssessmentDate: new Date('2026-02-01'),
    nextReviewDate: new Date('2026-08-01'),
    createdAt: new Date('2025-11-15'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'RSK-014',
    title: 'Third-Party Cloud Data Exfiltration',
    category: 'Cyber',
    description:
      'Data loss risk in cloud SaaS platforms. API security, access controls, and data residency concerns.',
    businessUnit: 'Technology',
    impact: 5,
    likelihood: 2,
    inherentScore: 10,
    residualScore: 5,
    owner: 'kevin.white@bank.com',
    status: 'Active',
    controlIds: ['CTL-034', 'CTL-035'],
    kpiIds: ['KRI-016'],
    lastAssessmentDate: new Date('2026-02-12'),
    nextReviewDate: new Date('2026-08-12'),
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2026-02-12'),
  },
  {
    id: 'RSK-015',
    title: 'Liquidity Coverage Ratio (LCR) Stress Scenario',
    category: 'Liquidity',
    description:
      'Funding liquidity stress testing assumptions. Deposit stability in crisis scenarios. Wholesale funding concentration.',
    businessUnit: 'Treasury',
    impact: 5,
    likelihood: 2,
    inherentScore: 10,
    residualScore: 6,
    owner: 'linda.lee@bank.com',
    status: 'Active',
    controlIds: ['CTL-036', 'CTL-037'],
    kpiIds: ['KRI-017'],
    lastAssessmentDate: new Date('2026-02-08'),
    nextReviewDate: new Date('2026-08-08'),
    createdAt: new Date('2025-06-10'),
    updatedAt: new Date('2026-02-08'),
  },
];

// ============================================================================
// CONTROLS - 20+ controls across Basel III, SOX, GDPR, NIST, ISO 27001
// ============================================================================

export const controls: Control[] = [
  {
    id: 'CTL-001',
    title: 'Commercial Real Estate Portfolio Concentration Limits',
    description: 'Establishes and monitors concentration limits for CRE exposures by product type and geography. Quarterly review against policy.',
    framework: 'Basel III',
    status: 'Implemented',
    owner: 'john.chen@bank.com',
    testDate: new Date('2026-02-10'),
    nextReviewDate: new Date('2026-08-10'),
    riskIds: ['RSK-001'],
    effectiveness: 'Effective',
    evidence: 'Portfolio_Concentration_Policy_v2.2.pdf',
    controlType: 'Detective',
    testFrequency: 'Quarterly',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'CTL-002',
    title: 'Credit Risk Stress Testing – CRE Scenarios',
    description: 'Stress tests CRE portfolio under various economic scenarios. Models loss severity under market downturns.',
    framework: 'Basel III',
    status: 'Implemented',
    owner: 'john.chen@bank.com',
    testDate: new Date('2026-01-25'),
    nextReviewDate: new Date('2026-07-25'),
    riskIds: ['RSK-001'],
    effectiveness: 'Effective',
    evidence: 'CCAR_CRE_Stress_Test_2026.xlsx',
    controlType: 'Detective',
    testFrequency: 'Annual',
    createdAt: new Date('2024-07-15'),
    updatedAt: new Date('2026-01-25'),
  },
  {
    id: 'CTL-003',
    title: 'LIBOR-SOFR Fallback Clause Validation',
    description: 'Systematic review and update of fallback language in legacy contracts. Automated detection of non-compliant terms.',
    framework: 'Basel III',
    status: 'Implemented',
    owner: 'sarah.martinez@bank.com',
    testDate: new Date('2026-01-15'),
    nextReviewDate: new Date('2026-10-15'),
    riskIds: ['RSK-002'],
    effectiveness: 'Effective',
    evidence: 'LIBOR_Transition_Inventory_2026.xlsx',
    controlType: 'Preventive',
    testFrequency: 'Semi-Annual',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'CTL-004',
    title: 'SOFR Basis Risk Hedging Strategy',
    description: 'Implements hedge strategy for residual LIBOR-SOFR basis risk. Daily monitoring of basis spreads.',
    framework: 'Basel III',
    status: 'Implemented',
    owner: 'sarah.martinez@bank.com',
    testDate: new Date('2026-02-01'),
    nextReviewDate: new Date('2026-08-01'),
    riskIds: ['RSK-002'],
    effectiveness: 'Effective',
    evidence: 'Basis_Hedge_Daily_Report.xlsx',
    controlType: 'Preventive',
    testFrequency: 'Quarterly',
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'CTL-005',
    title: 'Fallback Spread Publication Monitoring',
    description: 'Tracks and documents spread adjustments from regulatory bodies. Applies to customer contracts within SLA.',
    framework: 'Basel III',
    status: 'Implemented',
    owner: 'sarah.martinez@bank.com',
    testDate: new Date('2025-12-20'),
    nextReviewDate: new Date('2026-06-20'),
    riskIds: ['RSK-002'],
    effectiveness: 'Effective',
    evidence: 'Spread_Monitoring_Dashboard.html',
    controlType: 'Detective',
    testFrequency: 'Monthly',
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2025-12-20'),
  },
  {
    id: 'CTL-006',
    title: 'BSA/AML Model Validation Framework',
    description: 'Independent review and validation of transaction monitoring model. Ongoing tuning and threshold optimization.',
    framework: 'SOX',
    status: 'Partially Implemented',
    owner: 'michael.thompson@bank.com',
    testDate: new Date('2026-01-10'),
    nextReviewDate: new Date('2026-07-10'),
    riskIds: ['RSK-003'],
    effectiveness: 'Partially Effective',
    evidence: 'TM_Model_Validation_Q4_2025.pdf',
    controlType: 'Detective',
    testFrequency: 'Semi-Annual',
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2026-01-10'),
  },
  {
    id: 'CTL-007',
    title: 'SAR Filing Quality Assurance',
    description: 'Review process for all suspicious activity reports before submission to FinCEN. Case manager certification.',
    framework: 'SOX',
    status: 'Implemented',
    owner: 'michael.thompson@bank.com',
    testDate: new Date('2026-02-05'),
    nextReviewDate: new Date('2026-08-05'),
    riskIds: ['RSK-003'],
    effectiveness: 'Effective',
    evidence: 'SAR_QA_Process_Documentation.pdf',
    controlType: 'Preventive',
    testFrequency: 'Monthly',
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2026-02-05'),
  },
  {
    id: 'CTL-008',
    title: 'Threshold Tuning and Alert Override Review',
    description: 'Quarterly review of alert tuning parameters. Justification for threshold overrides and false positives.',
    framework: 'SOX',
    status: 'Implemented',
    owner: 'michael.thompson@bank.com',
    testDate: new Date('2026-02-15'),
    nextReviewDate: new Date('2026-08-15'),
    riskIds: ['RSK-003'],
    effectiveness: 'Effective',
    evidence: 'Alert_Tuning_Review_Q4_2025.xlsx',
    controlType: 'Detective',
    testFrequency: 'Quarterly',
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'CTL-009',
    title: 'Cloud Infrastructure Disaster Recovery Plan',
    description: 'Documents RTO/RPO for AWS systems. Tests failover procedures semi-annually. Backup infrastructure in secondary region.',
    framework: 'NIST',
    status: 'Implemented',
    owner: 'lisa.park@bank.com',
    testDate: new Date('2025-11-30'),
    nextReviewDate: new Date('2026-05-30'),
    riskIds: ['RSK-004'],
    effectiveness: 'Effective',
    evidence: 'DR_Plan_AWS_Infrastructure_2026.pdf',
    controlType: 'Preventive',
    testFrequency: 'Semi-Annual',
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2025-11-30'),
  },
  {
    id: 'CTL-010',
    title: 'Multi-Cloud Strategy Roadmap',
    description: 'Plans migration to multi-cloud architecture. Vendor diversification for critical services.',
    framework: 'NIST',
    status: 'Under Review',
    owner: 'lisa.park@bank.com',
    testDate: new Date('2025-12-10'),
    nextReviewDate: new Date('2026-06-10'),
    riskIds: ['RSK-004'],
    effectiveness: 'Partially Effective',
    evidence: 'Multi_Cloud_Roadmap_Draft_v1.1.pdf',
    controlType: 'Preventive',
    testFrequency: 'Annual',
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-12-10'),
  },
  {
    id: 'CTL-011',
    title: 'GDPR Data Transfer Impact Assessment',
    description: 'Documents adequacy of data transfer mechanisms to UK post-Brexit. Annual review of SCCs and BCRs.',
    framework: 'GDPR',
    status: 'Implemented',
    owner: 'emma.johnson@bank.com',
    testDate: new Date('2025-12-01'),
    nextReviewDate: new Date('2026-06-01'),
    riskIds: ['RSK-005'],
    effectiveness: 'Effective',
    evidence: 'GDPR_Data_Transfer_Assessment_2026.pdf',
    controlType: 'Preventive',
    testFrequency: 'Annual',
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2025-12-01'),
  },
  {
    id: 'CTL-012',
    title: 'Data Residency Enforcement Policy',
    description: 'Technical controls enforcing EU/UK data localization requirements. DLP rules and data classification.',
    framework: 'GDPR',
    status: 'Implemented',
    owner: 'emma.johnson@bank.com',
    testDate: new Date('2026-01-20'),
    nextReviewDate: new Date('2026-07-20'),
    riskIds: ['RSK-005'],
    effectiveness: 'Effective',
    evidence: 'Data_Residency_Control_Report.pdf',
    controlType: 'Preventive',
    testFrequency: 'Quarterly',
    createdAt: new Date('2025-01-25'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'CTL-013',
    title: 'Core Platform Migration Governance',
    description: 'Steering committee overseeing 3-year migration timeline. Monthly status reporting and risk escalation.',
    framework: 'SOX',
    status: 'Implemented',
    owner: 'robert.kumar@bank.com',
    testDate: new Date('2026-02-20'),
    nextReviewDate: new Date('2026-08-20'),
    riskIds: ['RSK-006'],
    effectiveness: 'Effective',
    evidence: 'Migration_Steering_Committee_Charter.pdf',
    controlType: 'Preventive',
    testFrequency: 'Monthly',
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'CTL-014',
    title: 'Parallel System Testing Plan',
    description: 'Dual-run testing of new platform against legacy system. Production parity validation.',
    framework: 'SOX',
    status: 'Partially Implemented',
    owner: 'robert.kumar@bank.com',
    testDate: new Date('2026-01-15'),
    nextReviewDate: new Date('2026-07-15'),
    riskIds: ['RSK-006'],
    effectiveness: 'Partially Effective',
    evidence: 'Test_Plan_Phase_2_2026.pdf',
    controlType: 'Detective',
    testFrequency: 'Quarterly',
    createdAt: new Date('2025-03-10'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'CTL-015',
    title: 'Data Migration Validation',
    description: 'Reconciliation controls for data migration from legacy to new platform. Completeness and accuracy checks.',
    framework: 'SOX',
    status: 'Implemented',
    owner: 'robert.kumar@bank.com',
    testDate: new Date('2026-02-10'),
    nextReviewDate: new Date('2026-08-10'),
    riskIds: ['RSK-006'],
    effectiveness: 'Effective',
    evidence: 'Data_Migration_Control_Specs.xlsx',
    controlType: 'Detective',
    testFrequency: 'Quarterly',
    createdAt: new Date('2025-04-20'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'CTL-016',
    title: 'Payments Vendor Redundancy Architecture',
    description: 'Backup vendor in hot-standby configuration. Automated failover for critical payment streams.',
    framework: 'NIST',
    status: 'Implemented',
    owner: 'james.wilson@bank.com',
    testDate: new Date('2026-01-20'),
    nextReviewDate: new Date('2026-07-20'),
    riskIds: ['RSK-007'],
    effectiveness: 'Effective',
    evidence: 'Payments_Failover_Test_Results.pdf',
    controlType: 'Preventive',
    testFrequency: 'Semi-Annual',
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'CTL-017',
    title: 'Payments Processing SLA Monitoring',
    description: 'Daily monitoring of vendor SLA compliance. Escalation procedures for breaches.',
    framework: 'NIST',
    status: 'Implemented',
    owner: 'james.wilson@bank.com',
    testDate: new Date('2026-02-15'),
    nextReviewDate: new Date('2026-08-15'),
    riskIds: ['RSK-007'],
    effectiveness: 'Effective',
    evidence: 'SLA_Dashboard_2026.html',
    controlType: 'Detective',
    testFrequency: 'Daily',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'CTL-018',
    title: 'Interest Rate Sensitivity Analysis',
    description: 'Daily EVE and NII sensitivity reporting. Gap analysis across repricing buckets.',
    framework: 'Basel III',
    status: 'Implemented',
    owner: 'david.lopez@bank.com',
    testDate: new Date('2026-02-18'),
    nextReviewDate: new Date('2026-08-18'),
    riskIds: ['RSK-008'],
    effectiveness: 'Effective',
    evidence: 'EVE_Sensitivity_Daily_Report.xlsx',
    controlType: 'Detective',
    testFrequency: 'Daily',
    createdAt: new Date('2025-05-12'),
    updatedAt: new Date('2026-02-18'),
  },
  {
    id: 'CTL-019',
    title: 'Deposit Beta Stress Testing',
    description: 'Quarterly review of deposit beta assumptions under stress scenarios. Historical analysis of deposit mobility.',
    framework: 'Basel III',
    status: 'Implemented',
    owner: 'david.lopez@bank.com',
    testDate: new Date('2026-02-01'),
    nextReviewDate: new Date('2026-08-01'),
    riskIds: ['RSK-008'],
    effectiveness: 'Effective',
    evidence: 'Deposit_Beta_Stress_Q4_2025.pdf',
    controlType: 'Detective',
    testFrequency: 'Quarterly',
    createdAt: new Date('2025-06-20'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'CTL-020',
    title: 'ALCO Interest Rate Policy',
    description: 'ALCO-approved policy setting IRRBB risk tolerance and management limits.',
    framework: 'Basel III',
    status: 'Implemented',
    owner: 'david.lopez@bank.com',
    testDate: new Date('2025-11-30'),
    nextReviewDate: new Date('2026-05-30'),
    riskIds: ['RSK-008'],
    effectiveness: 'Effective',
    evidence: 'ALCO_IRRBB_Policy_v3.2.pdf',
    controlType: 'Preventive',
    testFrequency: 'Annual',
    createdAt: new Date('2025-07-01'),
    updatedAt: new Date('2025-11-30'),
  },
  {
    id: 'CTL-021',
    title: 'Endpoint Detection and Response (EDR)',
    description: 'Enterprise EDR platform monitoring all endpoints. Real-time threat detection and response playbooks.',
    framework: 'NIST',
    status: 'Implemented',
    owner: 'catherine.davis@bank.com',
    testDate: new Date('2026-02-22'),
    nextReviewDate: new Date('2026-05-22'),
    riskIds: ['RSK-009'],
    effectiveness: 'Effective',
    evidence: 'EDR_Deployment_Report.pdf',
    controlType: 'Detective',
    testFrequency: 'Quarterly',
    createdAt: new Date('2025-08-10'),
    updatedAt: new Date('2026-02-22'),
  },
  {
    id: 'CTL-022',
    title: 'Ransomware Simulation Testing',
    description: 'Semi-annual tabletop exercises and technical simulations. Recovery procedures validation.',
    framework: 'NIST',
    status: 'Implemented',
    owner: 'catherine.davis@bank.com',
    testDate: new Date('2025-11-15'),
    nextReviewDate: new Date('2026-05-15'),
    riskIds: ['RSK-009'],
    effectiveness: 'Effective',
    evidence: 'Ransomware_Simulation_Report_H1_2025.pdf',
    controlType: 'Detective',
    testFrequency: 'Semi-Annual',
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2025-11-15'),
  },
  {
    id: 'CTL-023',
    title: 'Network Segmentation – OT/IT Isolation',
    description: 'Firewalls and network controls isolating critical OT systems from IT networks. Restricted access controls.',
    framework: 'NIST',
    status: 'Implemented',
    owner: 'catherine.davis@bank.com',
    testDate: new Date('2026-01-30'),
    nextReviewDate: new Date('2026-07-30'),
    riskIds: ['RSK-009'],
    effectiveness: 'Effective',
    evidence: 'Network_Segmentation_Audit.pdf',
    controlType: 'Preventive',
    testFrequency: 'Annual',
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2026-01-30'),
  },
  {
    id: 'CTL-024',
    title: 'Supply Chain Security Monitoring',
    description: 'Monitoring of vendor software/hardware for vulnerabilities. Vendor SBOMs collection and analysis.',
    framework: 'NIST',
    status: 'Partially Implemented',
    owner: 'catherine.davis@bank.com',
    testDate: new Date('2026-02-10'),
    nextReviewDate: new Date('2026-08-10'),
    riskIds: ['RSK-009'],
    effectiveness: 'Partially Effective',
    evidence: 'Supply_Chain_Security_Framework_v1.pdf',
    controlType: 'Detective',
    testFrequency: 'Quarterly',
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'CTL-025',
    title: 'Model Risk Management Governance',
    description: 'MRM framework and independent model validation. Documentation of assumptions and limitations.',
    framework: 'SOX',
    status: 'Implemented',
    owner: 'alice.brown@bank.com',
    testDate: new Date('2026-01-20'),
    nextReviewDate: new Date('2026-07-20'),
    riskIds: ['RSK-010'],
    effectiveness: 'Effective',
    evidence: 'Model_Risk_Framework_v2.3.pdf',
    controlType: 'Preventive',
    testFrequency: 'Annual',
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'CTL-026',
    title: 'CECL Model Performance Monitoring',
    description: 'Quarterly monitoring of CECL model performance. Back-testing accuracy against actual charge-offs.',
    framework: 'SOX',
    status: 'Implemented',
    owner: 'alice.brown@bank.com',
    testDate: new Date('2026-02-15'),
    nextReviewDate: new Date('2026-08-15'),
    riskIds: ['RSK-010'],
    effectiveness: 'Effective',
    evidence: 'CECL_Backtesting_Q4_2025.xlsx',
    controlType: 'Detective',
    testFrequency: 'Quarterly',
    createdAt: new Date('2025-11-15'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'CTL-027',
    title: 'Business Continuity Plan – Critical Services',
    description: 'Documents critical service dependencies. RTO/RPO targets and recovery procedures.',
    framework: 'NIST',
    status: 'Implemented',
    owner: 'marcus.anderson@bank.com',
    testDate: new Date('2025-12-01'),
    nextReviewDate: new Date('2026-06-01'),
    riskIds: ['RSK-011'],
    effectiveness: 'Effective',
    evidence: 'BCP_Critical_Services_2026.pdf',
    controlType: 'Preventive',
    testFrequency: 'Annual',
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2025-12-01'),
  },
  {
    id: 'CTL-028',
    title: 'Disaster Recovery Testing',
    description: 'Quarterly full DR tests. Validation of backup systems and data integrity.',
    framework: 'NIST',
    status: 'Implemented',
    owner: 'marcus.anderson@bank.com',
    testDate: new Date('2026-02-05'),
    nextReviewDate: new Date('2026-08-05'),
    riskIds: ['RSK-011'],
    effectiveness: 'Effective',
    evidence: 'DR_Test_Results_Q4_2025.pdf',
    controlType: 'Detective',
    testFrequency: 'Quarterly',
    createdAt: new Date('2025-12-10'),
    updatedAt: new Date('2026-02-05'),
  },
  {
    id: 'CTL-029',
    title: 'Alternate Processing Site Maintenance',
    description: 'Maintains alternate processing facility with synchronized data. Annual validation of failover readiness.',
    framework: 'NIST',
    status: 'Implemented',
    owner: 'marcus.anderson@bank.com',
    testDate: new Date('2025-10-15'),
    nextReviewDate: new Date('2026-04-15'),
    riskIds: ['RSK-011'],
    effectiveness: 'Effective',
    evidence: 'APS_Readiness_Report_2025.pdf',
    controlType: 'Preventive',
    testFrequency: 'Annual',
    createdAt: new Date('2025-12-15'),
    updatedAt: new Date('2025-10-15'),
  },
  {
    id: 'CTL-030',
    title: 'SA-CCR Implementation Validation',
    description: 'Validates SA-CCR model implementation against regulatory specifications. System testing and reconciliation.',
    framework: 'Basel III',
    status: 'Implemented',
    owner: 'patricia.garcia@bank.com',
    testDate: new Date('2026-01-25'),
    nextReviewDate: new Date('2026-07-25'),
    riskIds: ['RSK-012'],
    effectiveness: 'Effective',
    evidence: 'SA_CCR_Implementation_Report.pdf',
    controlType: 'Detective',
    testFrequency: 'Annual',
    createdAt: new Date('2025-12-20'),
    updatedAt: new Date('2026-01-25'),
  },
  {
    id: 'CTL-031',
    title: 'Derivative Pricing and Valuation Controls',
    description: 'Independent price verification for derivatives. Reconciliation of pricing models against market data.',
    framework: 'Basel III',
    status: 'Implemented',
    owner: 'patricia.garcia@bank.com',
    testDate: new Date('2026-02-20'),
    nextReviewDate: new Date('2026-08-20'),
    riskIds: ['RSK-012'],
    effectiveness: 'Effective',
    evidence: 'Derivative_Valuation_Control_Report.pdf',
    controlType: 'Detective',
    testFrequency: 'Daily',
    createdAt: new Date('2025-12-25'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'CTL-032',
    title: 'Fair Lending Policy and Procedures',
    description: 'Documents fair lending requirements. Loan pricing and underwriting procedures.',
    framework: 'SOX',
    status: 'Implemented',
    owner: 'stephanie.harris@bank.com',
    testDate: new Date('2026-01-30'),
    nextReviewDate: new Date('2026-07-30'),
    riskIds: ['RSK-013'],
    effectiveness: 'Effective',
    evidence: 'Fair_Lending_Policies_v2.1.pdf',
    controlType: 'Preventive',
    testFrequency: 'Annual',
    createdAt: new Date('2025-12-28'),
    updatedAt: new Date('2026-01-30'),
  },
  {
    id: 'CTL-033',
    title: 'Disparate Impact Testing – Quarterly',
    description: 'Quarterly disparate impact analysis of loan approvals and pricing by protected classes.',
    framework: 'SOX',
    status: 'Implemented',
    owner: 'stephanie.harris@bank.com',
    testDate: new Date('2026-02-20'),
    nextReviewDate: new Date('2026-08-20'),
    riskIds: ['RSK-013'],
    effectiveness: 'Effective',
    evidence: 'Disparate_Impact_Analysis_Q4_2025.xlsx',
    controlType: 'Detective',
    testFrequency: 'Quarterly',
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'CTL-034',
    title: 'Cloud Data Loss Prevention (DLP)',
    description: 'DLP policies and rules protecting data in SaaS applications. Classification and encryption controls.',
    framework: 'GDPR',
    status: 'Implemented',
    owner: 'kevin.white@bank.com',
    testDate: new Date('2026-02-10'),
    nextReviewDate: new Date('2026-08-10'),
    riskIds: ['RSK-014'],
    effectiveness: 'Effective',
    evidence: 'Cloud_DLP_Report.pdf',
    controlType: 'Preventive',
    testFrequency: 'Quarterly',
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'CTL-035',
    title: 'API Security – Authentication and Authorization',
    description: 'OAuth 2.0 implementation. API key rotation and access control enforcement.',
    framework: 'NIST',
    status: 'Implemented',
    owner: 'kevin.white@bank.com',
    testDate: new Date('2026-01-20'),
    nextReviewDate: new Date('2026-07-20'),
    riskIds: ['RSK-014'],
    effectiveness: 'Effective',
    evidence: 'API_Security_Assessment_2026.pdf',
    controlType: 'Preventive',
    testFrequency: 'Semi-Annual',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'CTL-036',
    title: 'LCR Calculation and Monitoring',
    description: 'Daily LCR calculation per Basel III rules. Regulatory reporting validation.',
    framework: 'Basel III',
    status: 'Implemented',
    owner: 'linda.lee@bank.com',
    testDate: new Date('2026-02-15'),
    nextReviewDate: new Date('2026-08-15'),
    riskIds: ['RSK-015'],
    effectiveness: 'Effective',
    evidence: 'LCR_Daily_Report.xlsx',
    controlType: 'Detective',
    testFrequency: 'Daily',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'CTL-037',
    title: 'Liquidity Stress Testing – CCAR/DFAST',
    description: 'Quarterly stress testing of liquidity under Fed scenarios. Funding gap analysis.',
    framework: 'Basel III',
    status: 'Implemented',
    owner: 'linda.lee@bank.com',
    testDate: new Date('2026-02-01'),
    nextReviewDate: new Date('2026-08-01'),
    riskIds: ['RSK-015'],
    effectiveness: 'Effective',
    evidence: 'CCAR_Liquidity_Stress_Test_2026.pdf',
    controlType: 'Detective',
    testFrequency: 'Quarterly',
    createdAt: new Date('2026-01-25'),
    updatedAt: new Date('2026-02-01'),
  },
];

// ============================================================================
// VENDORS - 8-10 third-party vendors with realistic attributes
// ============================================================================

export const vendors: Vendor[] = [
  {
    id: 'VND-001',
    name: 'Meridian Cloud Services',
    tier: 1,
    category: 'Cloud Infrastructure',
    criticality: 'Critical',
    dataSensitivity: 'High',
    inherentRisk: 4,
    residualRisk: 2,
    slaStatus: 'Green',
    contractExpiry: new Date('2027-12-31'),
    regulatoryRelevance: true,
    services: ['AWS EC2 Hosting', 'Cloud Database Services', 'Load Balancing'],
    location: 'United States',
    lastAssessmentDate: new Date('2026-02-10'),
    nextReviewDate: new Date('2026-08-10'),
    controlIds: ['CTL-009', 'CTL-010'],
    contractValue: 12500000,
    backupVendor: 'VND-008',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'VND-002',
    name: 'DataVault Analytics',
    tier: 1,
    category: 'Data Analytics & BI',
    criticality: 'High',
    dataSensitivity: 'High',
    inherentRisk: 3,
    residualRisk: 2,
    slaStatus: 'Green',
    contractExpiry: new Date('2027-06-30'),
    regulatoryRelevance: true,
    services: ['Data Warehouse', 'Analytics Platform', 'Reporting Tools'],
    location: 'United States',
    lastAssessmentDate: new Date('2026-01-25'),
    nextReviewDate: new Date('2026-07-25'),
    controlIds: ['CTL-012'],
    contractValue: 8750000,
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2026-01-25'),
  },
  {
    id: 'VND-003',
    name: 'SecureNet Cyber',
    tier: 2,
    category: 'Cybersecurity Services',
    criticality: 'High',
    dataSensitivity: 'High',
    inherentRisk: 3,
    residualRisk: 2,
    slaStatus: 'Green',
    contractExpiry: new Date('2026-12-31'),
    regulatoryRelevance: true,
    services: ['EDR Platform', 'Threat Intelligence', 'SIEM Support'],
    location: 'United States',
    lastAssessmentDate: new Date('2026-02-20'),
    nextReviewDate: new Date('2026-08-20'),
    controlIds: ['CTL-021', 'CTL-023'],
    contractValue: 3200000,
    createdAt: new Date('2023-11-10'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'VND-004',
    name: 'ComplianceEdge Solutions',
    tier: 2,
    category: 'Regulatory Compliance',
    criticality: 'Medium',
    dataSensitivity: 'High',
    inherentRisk: 2,
    residualRisk: 1,
    slaStatus: 'Green',
    contractExpiry: new Date('2027-03-31'),
    regulatoryRelevance: true,
    services: ['Regulatory Reporting', 'Policy Management', 'Compliance Monitoring'],
    location: 'United States',
    lastAssessmentDate: new Date('2026-02-05'),
    nextReviewDate: new Date('2026-08-05'),
    controlIds: ['CTL-006', 'CTL-007'],
    contractValue: 2100000,
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2026-02-05'),
  },
  {
    id: 'VND-005',
    name: 'PayStream Global',
    tier: 1,
    category: 'Payments Processing',
    criticality: 'Critical',
    dataSensitivity: 'High',
    inherentRisk: 3,
    residualRisk: 2,
    slaStatus: 'Green',
    contractExpiry: new Date('2028-09-30'),
    regulatoryRelevance: true,
    services: ['ACH Processing', 'Wire Transfer Services', 'Payment Gateway'],
    location: 'United States',
    lastAssessmentDate: new Date('2026-01-15'),
    nextReviewDate: new Date('2026-07-15'),
    controlIds: ['CTL-016', 'CTL-017'],
    contractValue: 15000000,
    backupVendor: 'VND-008',
    createdAt: new Date('2022-08-15'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'VND-006',
    name: 'Apex Document Management',
    tier: 3,
    category: 'Document Storage & Archival',
    criticality: 'Low',
    dataSensitivity: 'Low',
    inherentRisk: 2,
    residualRisk: 1,
    slaStatus: 'Yellow',
    contractExpiry: new Date('2026-08-31'),
    regulatoryRelevance: false,
    services: ['Document Storage', 'Archival', 'Search & Retrieval'],
    location: 'United States',
    lastAssessmentDate: new Date('2025-11-20'),
    nextReviewDate: new Date('2026-05-20'),
    controlIds: [],
    contractValue: 450000,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2025-11-20'),
  },
  {
    id: 'VND-007',
    name: 'TrustBridge KYC',
    tier: 2,
    category: 'KYC/AML Services',
    criticality: 'High',
    dataSensitivity: 'High',
    inherentRisk: 4,
    residualRisk: 2,
    slaStatus: 'Green',
    contractExpiry: new Date('2027-11-30'),
    regulatoryRelevance: true,
    services: ['KYC Database', 'Sanctions Screening', 'Customer Due Diligence'],
    location: 'United Kingdom',
    lastAssessmentDate: new Date('2026-02-10'),
    nextReviewDate: new Date('2026-08-10'),
    controlIds: ['CTL-011'],
    contractValue: 5600000,
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'VND-008',
    name: 'CloudScale Infrastructure',
    tier: 1,
    category: 'Cloud Infrastructure & DR',
    criticality: 'Critical',
    dataSensitivity: 'High',
    inherentRisk: 4,
    residualRisk: 2,
    slaStatus: 'Green',
    contractExpiry: new Date('2028-03-31'),
    regulatoryRelevance: true,
    services: ['Disaster Recovery', 'Backup Services', 'Redundant Infrastructure'],
    location: 'United States',
    lastAssessmentDate: new Date('2026-01-30'),
    nextReviewDate: new Date('2026-07-30'),
    controlIds: ['CTL-027', 'CTL-028', 'CTL-029'],
    contractValue: 9200000,
    createdAt: new Date('2023-02-10'),
    updatedAt: new Date('2026-01-30'),
  },
  {
    id: 'VND-009',
    name: 'RegTech Dynamics',
    tier: 3,
    category: 'Regulatory Technology',
    criticality: 'Medium',
    dataSensitivity: 'Medium',
    inherentRisk: 2,
    residualRisk: 1,
    slaStatus: 'Green',
    contractExpiry: new Date('2026-12-31'),
    regulatoryRelevance: true,
    services: ['Risk Monitoring', 'Regulatory Dashboard', 'Alert System'],
    location: 'United States',
    lastAssessmentDate: new Date('2025-12-10'),
    nextReviewDate: new Date('2026-06-10'),
    controlIds: [],
    contractValue: 780000,
    createdAt: new Date('2024-07-15'),
    updatedAt: new Date('2025-12-10'),
  },
  {
    id: 'VND-010',
    name: 'QuantRisk Modeling',
    tier: 2,
    category: 'Risk Modeling & Validation',
    criticality: 'High',
    dataSensitivity: 'High',
    inherentRisk: 3,
    residualRisk: 2,
    slaStatus: 'Green',
    contractExpiry: new Date('2027-05-31'),
    regulatoryRelevance: true,
    services: ['Model Development', 'Model Validation', 'Backtesting'],
    location: 'United States',
    lastAssessmentDate: new Date('2026-02-15'),
    nextReviewDate: new Date('2026-08-15'),
    controlIds: ['CTL-025', 'CTL-026', 'CTL-030', 'CTL-031'],
    contractValue: 4300000,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2026-02-15'),
  },
];

// ============================================================================
// ISSUES / FINDINGS - 10+ audit findings and compliance issues
// ============================================================================

export const issues: Issue[] = [
  {
    id: 'ISS-001',
    title: 'BSA/AML Model Validation – Alert Tuning Gaps',
    severity: 'High',
    source: 'Internal Audit',
    status: 'In Progress',
    owner: 'michael.thompson@bank.com',
    dueDate: new Date('2026-05-30'),
    riskIds: ['RSK-003'],
    controlIds: ['CTL-006', 'CTL-008'],
    remediationPlan: 'Engage independent model validator to review thresholds and false positive rates. Target 50% reduction in alert volume by Q2 2026.',
    remediationDueDate: new Date('2026-05-30'),
    mraType: 'MRA',
    rootCause: 'Legacy model not adapted to current transaction patterns. Insufficient tuning resources.',
    impactStatement: 'Current 8% false positive rate creates alert fatigue for investigators.',
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'ISS-002',
    title: 'Cloud Infrastructure – Multi-Cloud Roadmap Delayed',
    severity: 'High',
    source: 'Self-Identified',
    status: 'Remediation Planned',
    owner: 'lisa.park@bank.com',
    dueDate: new Date('2026-06-30'),
    riskIds: ['RSK-004'],
    controlIds: ['CTL-010'],
    remediationPlan: 'Accelerate multi-cloud strategy implementation. Complete RFP for secondary cloud provider by Q2 2026.',
    remediationDueDate: new Date('2026-06-30'),
    mraType: 'MRIA',
    rootCause: 'Resource constraints and competing IT priorities.',
    impactStatement: 'Single vendor dependency creates operational risk.',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'ISS-003',
    title: 'GDPR Data Transfer – UK Adequacy Reassessment Overdue',
    severity: 'High',
    source: 'Regulatory Exam',
    status: 'Open',
    owner: 'emma.johnson@bank.com',
    dueDate: new Date('2026-04-30'),
    riskIds: ['RSK-005'],
    controlIds: ['CTL-011'],
    remediationPlan: 'Conduct comprehensive data flow mapping. Review SCCs and BCR implementation.',
    remediationDueDate: new Date('2026-04-30'),
    mraType: 'MRA',
    rootCause: 'Regulatory guidance changes and evolving legal interpretation.',
    impactStatement: 'Current data transfer mechanisms may not meet regulatory standards.',
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'ISS-004',
    title: 'Core Platform Migration – Budget and Timeline at Risk',
    severity: 'Critical',
    source: 'Internal Audit',
    status: 'Open',
    owner: 'robert.kumar@bank.com',
    dueDate: new Date('2026-03-31'),
    riskIds: ['RSK-006'],
    controlIds: ['CTL-013', 'CTL-014', 'CTL-015'],
    remediationPlan: 'Steering committee to review budget assumptions and timeline. Consider phased rollout approach.',
    remediationDueDate: new Date('2026-03-31'),
    mraType: 'MRA',
    rootCause: 'Scope creep and underestimated complexity of legacy system integration.',
    impactStatement: 'Project budget increased 15% with timeline extension of 6 months.',
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2026-02-18'),
  },
  {
    id: 'ISS-005',
    title: 'Cybersecurity – Supply Chain Risk Assessment Not Current',
    severity: 'Medium',
    source: 'Regulatory Exam',
    status: 'In Progress',
    owner: 'catherine.davis@bank.com',
    dueDate: new Date('2026-06-30'),
    riskIds: ['RSK-009'],
    controlIds: ['CTL-024'],
    remediationPlan: 'Implement vendor SBOM collection process. Quarterly risk assessment of key suppliers.',
    remediationDueDate: new Date('2026-06-30'),
    mraType: null,
    rootCause: 'Lack of automated vendor assessment tools and resource constraints.',
    impactStatement: 'Third-party vulnerability visibility is limited.',
    createdAt: new Date('2025-11-10'),
    updatedAt: new Date('2026-02-12'),
  },
  {
    id: 'ISS-006',
    title: 'Model Risk – CECL Model Validation Documentation Gaps',
    severity: 'Medium',
    source: 'External Audit',
    status: 'In Progress',
    owner: 'alice.brown@bank.com',
    dueDate: new Date('2026-04-30'),
    riskIds: ['RSK-010'],
    controlIds: ['CTL-025', 'CTL-026'],
    remediationPlan: 'Complete model validation documentation per MRM standards. Include assumption justification and sensitivity analysis.',
    remediationDueDate: new Date('2026-04-30'),
    mraType: 'MRA',
    rootCause: 'Model change pace exceeded documentation capability.',
    impactStatement: 'Model assumptions not fully documented.',
    createdAt: new Date('2025-12-20'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'ISS-007',
    title: 'Operational Resilience – RTO/RPO Gap Analysis Required',
    severity: 'High',
    source: 'Internal Audit',
    status: 'Remediation Planned',
    owner: 'marcus.anderson@bank.com',
    dueDate: new Date('2026-05-31'),
    riskIds: ['RSK-011'],
    controlIds: ['CTL-027', 'CTL-028'],
    remediationPlan: 'Conduct comprehensive critical service mapping. Identify and remediate RTO/RPO gaps.',
    remediationDueDate: new Date('2026-05-31'),
    mraType: 'MRIA',
    rootCause: 'Legacy RTO/RPO targets not aligned with current regulatory expectations.',
    impactStatement: 'Certain services have recovery objectives exceeding regulatory requirements.',
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-02-08'),
  },
  {
    id: 'ISS-008',
    title: 'Consumer Compliance – Fair Lending Training Overdue',
    severity: 'Medium',
    source: 'Self-Identified',
    status: 'In Progress',
    owner: 'stephanie.harris@bank.com',
    dueDate: new Date('2026-03-31'),
    riskIds: ['RSK-013'],
    controlIds: ['CTL-032', 'CTL-033'],
    remediationPlan: 'Conduct annual fair lending training for all lending staff. Update training materials with 2026 regulatory guidance.',
    remediationDueDate: new Date('2026-03-31'),
    mraType: null,
    rootCause: 'Annual training cycle delayed due to curriculum updates.',
    impactStatement: '300+ lending staff training completion rate at 72%.',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'ISS-009',
    title: 'Cloud SaaS – API Security Access Controls Not Documented',
    severity: 'Medium',
    source: 'Internal Audit',
    status: 'Open',
    owner: 'kevin.white@bank.com',
    dueDate: new Date('2026-04-30'),
    riskIds: ['RSK-014'],
    controlIds: ['CTL-034', 'CTL-035'],
    remediationPlan: 'Document API security architecture and access control design. Conduct annual penetration testing.',
    remediationDueDate: new Date('2026-04-30'),
    mraType: 'MRA',
    rootCause: 'API implementation predates current security documentation standards.',
    impactStatement: 'API access controls not formally validated.',
    createdAt: new Date('2026-01-25'),
    updatedAt: new Date('2026-02-05'),
  },
  {
    id: 'ISS-010',
    title: 'Liquidity – LCR Stress Assumption Reassessment Needed',
    severity: 'Medium',
    source: 'Regulatory Exam',
    status: 'In Progress',
    owner: 'linda.lee@bank.com',
    dueDate: new Date('2026-05-31'),
    riskIds: ['RSK-015'],
    controlIds: ['CTL-036', 'CTL-037'],
    remediationPlan: 'Update deposit stability assumptions based on 2025 stress testing results. Validate against current market conditions.',
    remediationDueDate: new Date('2026-05-31'),
    mraType: 'MRA',
    rootCause: 'Regulatory environment changes and market volatility require reassessment.',
    impactStatement: 'Current assumptions may not reflect current market environment.',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'ISS-011',
    title: 'Payments Processing – Backup Vendor SLA Not Formalized',
    severity: 'High',
    source: 'Internal Audit',
    status: 'Remediation Planned',
    owner: 'james.wilson@bank.com',
    dueDate: new Date('2026-04-30'),
    riskIds: ['RSK-007'],
    controlIds: ['CTL-017'],
    remediationPlan: 'Finalize backup vendor SLA terms and implement monitoring dashboard.',
    remediationDueDate: new Date('2026-04-30'),
    mraType: 'MRA',
    rootCause: 'Backup vendor contract still in negotiation phase.',
    impactStatement: 'Backup vendor failover procedures not formally defined.',
    createdAt: new Date('2026-01-30'),
    updatedAt: new Date('2026-02-12'),
  },
];

// ============================================================================
// LOSS EVENTS - 5+ loss events
// ============================================================================

export const lossEvents: LossEvent[] = [
  {
    id: 'LSS-001',
    title: 'CRE Loan Default – Commercial Office Building Portfolio',
    category: 'Credit',
    amount: 8200000,
    date: new Date('2025-09-15'),
    businessUnit: 'Commercial Banking',
    riskIds: ['RSK-001'],
    rootCause: 'Tenant default in soft office market. Post-COVID occupancy decline.',
    status: 'Resolved',
    description: 'Office property in secondary market with 40% occupancy decline triggered covenant breach and default.',
    recoveryAmount: 1200000,
    regulatoryReporting: true,
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2026-01-30'),
  },
  {
    id: 'LSS-002',
    title: 'Interest Rate Risk – Deposit Beta Misjudgment',
    category: 'Market',
    amount: 3150000,
    date: new Date('2025-12-01'),
    businessUnit: 'Treasury',
    riskIds: ['RSK-008'],
    rootCause: 'Deposit repricing beta assumption higher than historical. Rapid deposit outflow in rate increase scenario.',
    status: 'Resolved',
    description: 'Economic value loss from deposit outflows exceeding model expectations in rising rate environment.',
    recoveryAmount: 0,
    regulatoryReporting: false,
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'LSS-003',
    title: 'Ransomware Incident – Corporate Network Segment',
    category: 'Cyber',
    amount: 2750000,
    date: new Date('2025-07-20'),
    businessUnit: 'Technology',
    riskIds: ['RSK-009'],
    rootCause: 'Phishing email compromise of admin credentials. Lateral movement to backup systems.',
    status: 'Resolved',
    description: 'Ransomware deployment in corporate segment required backup restoration and operational disruption.',
    recoveryAmount: 450000,
    regulatoryReporting: false,
    createdAt: new Date('2025-07-20'),
    updatedAt: new Date('2026-02-05'),
  },
  {
    id: 'LSS-004',
    title: 'Third-Party Vendor Data Breach – KYC Vendor Incident',
    category: 'ThirdParty',
    amount: 1200000,
    date: new Date('2025-11-10'),
    businessUnit: 'Risk Management',
    riskIds: ['RSK-014'],
    rootCause: 'Vendor security incident exposing customer PII. Notification and credit monitoring costs.',
    status: 'Resolved',
    description: 'Vendor-caused data breach of 125,000 customer records. Remediation and notification costs.',
    recoveryAmount: 0,
    regulatoryReporting: true,
    createdAt: new Date('2025-11-10'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'LSS-005',
    title: 'Operational Error – Wire Transfer Misdirection',
    category: 'Operational',
    amount: 4500000,
    date: new Date('2025-08-12'),
    businessUnit: 'Operations',
    riskIds: ['RSK-011'],
    rootCause: 'Manual entry error in wire routing. Insufficient controls over high-value transactions.',
    status: 'Resolved',
    description: 'Wire transfer routed to incorrect customer account. Recovered through customer cooperation.',
    recoveryAmount: 4500000,
    regulatoryReporting: false,
    createdAt: new Date('2025-08-12'),
    updatedAt: new Date('2025-10-15'),
  },
  {
    id: 'LSS-006',
    title: 'Model Risk – CECL Reserve Inadequacy',
    category: 'Credit',
    amount: 6750000,
    date: new Date('2026-01-31'),
    businessUnit: 'Risk Management',
    riskIds: ['RSK-010'],
    rootCause: 'Model underestimated charge-off rates in commercial segment. Macro scenario selection.',
    status: 'Reported',
    description: 'Quarterly model review identified reserve deficiency requiring adjustment.',
    recoveryAmount: 0,
    regulatoryReporting: true,
    createdAt: new Date('2026-01-31'),
    updatedAt: new Date('2026-02-15'),
  },
];

// ============================================================================
// KEY RISK INDICATORS (KRIs) - 10+ KRIs with realistic thresholds
// ============================================================================

export const kris: KRI[] = [
  {
    id: 'KRI-001',
    name: 'CRE Concentration Ratio – All Properties',
    riskCategory: 'Credit',
    currentValue: 24.5,
    threshold: 20.0,
    breachLevel: 'Warning',
    trend: 'Deteriorating',
    unit: '%',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 22.1, date: new Date('2025-11-30') },
      { value: 22.8, date: new Date('2025-12-31') },
      { value: 23.5, date: new Date('2026-01-31') },
      { value: 24.5, date: new Date('2026-02-20') },
    ],
    owner: 'john.chen@bank.com',
    updateFrequency: 'Monthly',
    warningThreshold: 20.0,
    criticalThreshold: 25.0,
    createdAt: new Date('2024-06-01'),
  },
  {
    id: 'KRI-002',
    name: 'CRE Office Vacancy Rate',
    riskCategory: 'Credit',
    currentValue: 18.2,
    threshold: 15.0,
    breachLevel: 'Breach',
    trend: 'Deteriorating',
    unit: '%',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 14.5, date: new Date('2025-08-31') },
      { value: 16.2, date: new Date('2025-11-30') },
      { value: 17.1, date: new Date('2026-01-31') },
      { value: 18.2, date: new Date('2026-02-20') },
    ],
    owner: 'john.chen@bank.com',
    updateFrequency: 'Quarterly',
    warningThreshold: 15.0,
    criticalThreshold: 20.0,
    createdAt: new Date('2024-06-01'),
  },
  {
    id: 'KRI-003',
    name: 'LIBOR-SOFR Basis Spread',
    riskCategory: 'Market',
    currentValue: 8.5,
    threshold: 12.0,
    breachLevel: 'Normal',
    trend: 'Stable',
    unit: 'bps',
    lastUpdated: new Date('2026-02-21'),
    historicalValues: [
      { value: 9.2, date: new Date('2025-12-01') },
      { value: 8.8, date: new Date('2026-01-15') },
      { value: 8.5, date: new Date('2026-02-21') },
    ],
    owner: 'sarah.martinez@bank.com',
    updateFrequency: 'Daily',
    warningThreshold: 12.0,
    criticalThreshold: 15.0,
    createdAt: new Date('2024-03-01'),
  },
  {
    id: 'KRI-004',
    name: 'BSA/AML Alert False Positive Rate',
    riskCategory: 'Compliance',
    currentValue: 8.2,
    threshold: 5.0,
    breachLevel: 'Warning',
    trend: 'Stable',
    unit: '%',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 9.1, date: new Date('2025-11-30') },
      { value: 8.5, date: new Date('2026-01-31') },
      { value: 8.2, date: new Date('2026-02-20') },
    ],
    owner: 'michael.thompson@bank.com',
    updateFrequency: 'Weekly',
    warningThreshold: 5.0,
    criticalThreshold: 10.0,
    createdAt: new Date('2025-03-20'),
  },
  {
    id: 'KRI-005',
    name: 'Suspicious Activity Reports (SARs) per 10k Transactions',
    riskCategory: 'Compliance',
    currentValue: 12.3,
    threshold: 8.0,
    breachLevel: 'Warning',
    trend: 'Deteriorating',
    unit: 'count',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 10.2, date: new Date('2025-08-31') },
      { value: 11.5, date: new Date('2025-11-30') },
      { value: 12.3, date: new Date('2026-02-20') },
    ],
    owner: 'michael.thompson@bank.com',
    updateFrequency: 'Monthly',
    warningThreshold: 8.0,
    criticalThreshold: 15.0,
    createdAt: new Date('2025-03-20'),
  },
  {
    id: 'KRI-006',
    name: 'Cloud Infrastructure – AWS Dependency Score',
    riskCategory: 'ThirdParty',
    currentValue: 85,
    threshold: 70,
    breachLevel: 'Breach',
    trend: 'Stable',
    unit: '%',
    lastUpdated: new Date('2026-02-15'),
    historicalValues: [
      { value: 87, date: new Date('2025-11-30') },
      { value: 86, date: new Date('2026-01-15') },
      { value: 85, date: new Date('2026-02-15') },
    ],
    owner: 'lisa.park@bank.com',
    updateFrequency: 'Quarterly',
    warningThreshold: 70,
    criticalThreshold: 80,
    createdAt: new Date('2025-05-10'),
  },
  {
    id: 'KRI-007',
    name: 'Cross-Border Data Transfers – EU/UK Volume (GB)',
    riskCategory: 'Compliance',
    currentValue: 245.7,
    threshold: 500.0,
    breachLevel: 'Normal',
    trend: 'Stable',
    unit: 'GB',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 238.2, date: new Date('2025-12-31') },
      { value: 242.1, date: new Date('2026-01-31') },
      { value: 245.7, date: new Date('2026-02-20') },
    ],
    owner: 'emma.johnson@bank.com',
    updateFrequency: 'Monthly',
    warningThreshold: 500.0,
    criticalThreshold: 750.0,
    createdAt: new Date('2025-01-08'),
  },
  {
    id: 'KRI-008',
    name: 'Core Platform Migration – Schedule Variance',
    riskCategory: 'Operational',
    currentValue: 6,
    threshold: 2,
    breachLevel: 'Breach',
    trend: 'Deteriorating',
    unit: 'months',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 2, date: new Date('2025-08-31') },
      { value: 4, date: new Date('2025-11-30') },
      { value: 6, date: new Date('2026-02-20') },
    ],
    owner: 'robert.kumar@bank.com',
    updateFrequency: 'Monthly',
    warningThreshold: 2,
    criticalThreshold: 8,
    createdAt: new Date('2025-02-20'),
  },
  {
    id: 'KRI-009',
    name: 'Payments Processing – Vendor Concentration',
    riskCategory: 'ThirdParty',
    currentValue: 85.3,
    threshold: 75.0,
    breachLevel: 'Warning',
    trend: 'Stable',
    unit: '%',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 85.1, date: new Date('2025-11-30') },
      { value: 85.2, date: new Date('2026-01-31') },
      { value: 85.3, date: new Date('2026-02-20') },
    ],
    owner: 'james.wilson@bank.com',
    updateFrequency: 'Monthly',
    warningThreshold: 75.0,
    criticalThreshold: 90.0,
    createdAt: new Date('2024-11-05'),
  },
  {
    id: 'KRI-010',
    name: 'Interest Rate Sensitivity – EVE Impact ($ millions)',
    riskCategory: 'Market',
    currentValue: 125.8,
    threshold: 150.0,
    breachLevel: 'Normal',
    trend: 'Stable',
    unit: '$M',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 118.2, date: new Date('2025-11-30') },
      { value: 121.5, date: new Date('2026-01-15') },
      { value: 125.8, date: new Date('2026-02-20') },
    ],
    owner: 'david.lopez@bank.com',
    updateFrequency: 'Daily',
    warningThreshold: 150.0,
    criticalThreshold: 200.0,
    createdAt: new Date('2025-04-12'),
  },
  {
    id: 'KRI-011',
    name: 'Cyber – Unpatched Critical Vulnerabilities',
    riskCategory: 'Cyber',
    currentValue: 12,
    threshold: 5,
    breachLevel: 'Warning',
    trend: 'Improving',
    unit: 'count',
    lastUpdated: new Date('2026-02-21'),
    historicalValues: [
      { value: 28, date: new Date('2025-11-30') },
      { value: 18, date: new Date('2026-01-15') },
      { value: 12, date: new Date('2026-02-21') },
    ],
    owner: 'catherine.davis@bank.com',
    updateFrequency: 'Weekly',
    warningThreshold: 5,
    criticalThreshold: 20,
    createdAt: new Date('2025-07-01'),
  },
  {
    id: 'KRI-012',
    name: 'Model Risk – CECL Reserve Coverage Ratio',
    riskCategory: 'Credit',
    currentValue: 1.42,
    threshold: 1.50,
    breachLevel: 'Warning',
    trend: 'Stable',
    unit: 'ratio',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 1.48, date: new Date('2025-12-31') },
      { value: 1.45, date: new Date('2026-01-31') },
      { value: 1.42, date: new Date('2026-02-20') },
    ],
    owner: 'alice.brown@bank.com',
    updateFrequency: 'Monthly',
    warningThreshold: 1.50,
    criticalThreshold: 1.40,
    createdAt: new Date('2025-08-15'),
  },
  {
    id: 'KRI-013',
    name: 'Operational Resilience – RTO Compliance Gap',
    riskCategory: 'Operational',
    currentValue: 8,
    threshold: 2,
    breachLevel: 'Breach',
    trend: 'Stable',
    unit: 'services',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 8, date: new Date('2025-11-30') },
      { value: 8, date: new Date('2026-01-31') },
      { value: 8, date: new Date('2026-02-20') },
    ],
    owner: 'marcus.anderson@bank.com',
    updateFrequency: 'Quarterly',
    warningThreshold: 2,
    criticalThreshold: 10,
    createdAt: new Date('2025-09-20'),
  },
  {
    id: 'KRI-014',
    name: 'Regulatory Capital – SA-CCR Implementation Progress',
    riskCategory: 'Compliance',
    currentValue: 78,
    threshold: 100,
    breachLevel: 'Warning',
    trend: 'Improving',
    unit: '%',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 65, date: new Date('2025-11-30') },
      { value: 72, date: new Date('2026-01-15') },
      { value: 78, date: new Date('2026-02-20') },
    ],
    owner: 'patricia.garcia@bank.com',
    updateFrequency: 'Monthly',
    warningThreshold: 100,
    criticalThreshold: 50,
    createdAt: new Date('2025-10-10'),
  },
  {
    id: 'KRI-015',
    name: 'Fair Lending – Disparate Impact Score',
    riskCategory: 'Compliance',
    currentValue: 1.04,
    threshold: 1.25,
    breachLevel: 'Normal',
    trend: 'Stable',
    unit: 'ratio',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 1.02, date: new Date('2025-11-30') },
      { value: 1.03, date: new Date('2026-01-31') },
      { value: 1.04, date: new Date('2026-02-20') },
    ],
    owner: 'stephanie.harris@bank.com',
    updateFrequency: 'Quarterly',
    warningThreshold: 1.25,
    criticalThreshold: 1.50,
    createdAt: new Date('2025-11-15'),
  },
  {
    id: 'KRI-016',
    name: 'Cloud SaaS – Encryption Coverage',
    riskCategory: 'Cyber',
    currentValue: 92,
    threshold: 95,
    breachLevel: 'Normal',
    trend: 'Improving',
    unit: '%',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 88, date: new Date('2025-11-30') },
      { value: 90, date: new Date('2026-01-31') },
      { value: 92, date: new Date('2026-02-20') },
    ],
    owner: 'kevin.white@bank.com',
    updateFrequency: 'Monthly',
    warningThreshold: 95,
    criticalThreshold: 90,
    createdAt: new Date('2025-12-01'),
  },
  {
    id: 'KRI-017',
    name: 'Liquidity Coverage Ratio (LCR)',
    riskCategory: 'Liquidity',
    currentValue: 1.38,
    threshold: 1.00,
    breachLevel: 'Normal',
    trend: 'Improving',
    unit: 'ratio',
    lastUpdated: new Date('2026-02-20'),
    historicalValues: [
      { value: 1.35, date: new Date('2025-11-30') },
      { value: 1.36, date: new Date('2026-01-31') },
      { value: 1.38, date: new Date('2026-02-20') },
    ],
    owner: 'linda.lee@bank.com',
    updateFrequency: 'Daily',
    warningThreshold: 1.00,
    criticalThreshold: 0.95,
    createdAt: new Date('2025-06-10'),
  },
];

// ============================================================================
// REGULATORY CHANGES - 6-7 realistic Basel III, prudential, and privacy updates
// ============================================================================

export const regulatoryChanges: RegulatoryChange[] = [
  {
    id: 'REG-001',
    title: 'Operational Resilience Final Rule – Critical Service Definition',
    source: 'Federal Reserve',
    effectiveDate: new Date('2026-10-01'),
    status: 'Impact Assessment',
    impactLevel: 'High',
    summary: 'Final rule establishing operational resilience framework for large banking organizations. Requires identification of critical services and tolerance for disruption.',
    affectedFrameworks: ['Basel III', 'SOX'],
    affectedControlIds: ['CTL-027', 'CTL-028', 'CTL-029'],
    actionPlanOwner: 'marcus.anderson@bank.com',
    actionPlanDueDate: new Date('2026-08-01'),
    implementationNotes: 'Requires mapping critical services to regulatory definition and establishing impact tolerance.',
    createdAt: new Date('2025-12-10'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'REG-002',
    title: 'Cybersecurity Risk Management – Board Oversight Requirements',
    source: 'OCC',
    effectiveDate: new Date('2026-09-01'),
    status: 'Impact Assessment',
    impactLevel: 'High',
    summary: 'OCC guidance on cybersecurity risk management. Requires board-level oversight, incident reporting, and third-party risk assessment.',
    affectedFrameworks: ['NIST', 'SOX'],
    affectedControlIds: ['CTL-021', 'CTL-022', 'CTL-023', 'CTL-024'],
    actionPlanOwner: 'catherine.davis@bank.com',
    actionPlanDueDate: new Date('2026-07-01'),
    implementationNotes: 'Board committee governance structure needs enhancement.',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'REG-003',
    title: 'Basel III Endgame – Revised Standardized Approaches',
    source: 'Basel Committee',
    effectiveDate: new Date('2027-01-01'),
    status: 'Monitoring',
    impactLevel: 'High',
    summary: 'Proposed Basel III revisions affecting credit risk, operational risk, and market risk calculations. Expected impact on capital requirements.',
    affectedFrameworks: ['Basel III'],
    affectedControlIds: ['CTL-001', 'CTL-002', 'CTL-030', 'CTL-031'],
    actionPlanOwner: 'patricia.garcia@bank.com',
    actionPlanDueDate: new Date('2026-12-31'),
    implementationNotes: 'Pending final rule publication. Preparing system impacts.',
    createdAt: new Date('2025-11-15'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'REG-004',
    title: 'Data Privacy – Proposed Amendments to GDPR Article 6',
    source: 'EU Commission',
    effectiveDate: new Date('2027-06-01'),
    status: 'Monitoring',
    impactLevel: 'Medium',
    summary: 'Proposed amendments to lawful basis for processing. Impact on cross-border data transfers and consent frameworks.',
    affectedFrameworks: ['GDPR'],
    affectedControlIds: ['CTL-011', 'CTL-012'],
    actionPlanOwner: 'emma.johnson@bank.com',
    actionPlanDueDate: new Date('2027-03-01'),
    implementationNotes: 'Monitoring legislative progress. May impact UK data transfer controls.',
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'REG-005',
    title: 'Model Risk Management – MRM Governance Update',
    source: 'Federal Reserve',
    effectiveDate: new Date('2026-12-31'),
    status: 'Implementation',
    impactLevel: 'Medium',
    summary: 'Revised SR 11-7 guidance on model risk management. Enhanced governance, validation, and monitoring requirements.',
    affectedFrameworks: ['SOX'],
    affectedControlIds: ['CTL-025', 'CTL-026'],
    actionPlanOwner: 'alice.brown@bank.com',
    actionPlanDueDate: new Date('2026-11-30'),
    implementationNotes: 'Drafting updated MRM policies and procedures.',
    createdAt: new Date('2025-10-20'),
    updatedAt: new Date('2026-02-05'),
  },
  {
    id: 'REG-006',
    title: 'SOFR Conversion – Remaining Legacy LIBOR Exposure',
    source: 'Federal Reserve',
    effectiveDate: new Date('2026-06-30'),
    status: 'Implementation',
    impactLevel: 'High',
    summary: 'Mandatory LIBOR discontinuation. All remaining LIBOR exposures must transition to SOFR or other alternatives.',
    affectedFrameworks: ['Basel III'],
    affectedControlIds: ['CTL-003', 'CTL-004', 'CTL-005'],
    actionPlanOwner: 'sarah.martinez@bank.com',
    actionPlanDueDate: new Date('2026-06-01'),
    implementationNotes: '2% of portfolio remains on LIBOR. Targeted customer outreach ongoing.',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'REG-007',
    title: 'Third-Party Risk Management – TPRM Standards',
    source: 'OCC',
    effectiveDate: new Date('2026-12-01'),
    status: 'Implementation',
    impactLevel: 'High',
    summary: 'Updated OCC guidance on third-party relationships. Enhanced due diligence, monitoring, and exit strategy requirements.',
    affectedFrameworks: ['SOX', 'NIST'],
    affectedControlIds: ['CTL-009', 'CTL-016', 'CTL-024'],
    actionPlanOwner: 'lisa.park@bank.com',
    actionPlanDueDate: new Date('2026-10-31'),
    implementationNotes: 'Enhancing vendor assessment framework and SLA enforcement.',
    createdAt: new Date('2025-09-10'),
    updatedAt: new Date('2026-02-10'),
  },
];

// ============================================================================
// RISK SCENARIOS - Sample scenario analysis
// ============================================================================

export const riskScenarios: RiskScenario[] = [
  {
    id: 'SCN-001',
    title: 'Commercial Real Estate Market Downturn Scenario',
    businessLine: 'Commercial Banking',
    product: 'CRE Lending',
    geography: 'United States',
    riskType: 'Credit',
    inherentRisk: 5,
    controlStrength: 3,
    lossHistory: [
      { amount: 8200000, date: new Date('2025-09-15') },
      { amount: 3400000, date: new Date('2024-06-20') },
    ],
    compositeScore: 15,
    narrative:
      'Scenario: 25% decline in commercial real estate values. Office vacancy increases to 20%+. Tenant defaults accelerate. Bank CRE portfolio experiences mark-to-market losses and covenant breaches.',
    probability: 35,
    potentialLoss: 45000000,
    mitigatingControls: ['CTL-001', 'CTL-002'],
    owner: 'john.chen@bank.com',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'SCN-002',
    title: 'Rapid Interest Rate Increase Scenario',
    businessLine: 'Treasury',
    product: 'Deposit & Lending Portfolio',
    geography: 'United States',
    riskType: 'Market',
    inherentRisk: 4,
    controlStrength: 4,
    lossHistory: [
      { amount: 3150000, date: new Date('2025-12-01') },
    ],
    compositeScore: 8,
    narrative:
      'Scenario: Federal Reserve raises rates 200 bps in 6 months. Deposit repricing beta higher than expected. NII compression. Deposit outflows to money market alternatives.',
    probability: 25,
    potentialLoss: 28000000,
    mitigatingControls: ['CTL-018', 'CTL-019', 'CTL-020'],
    owner: 'david.lopez@bank.com',
    createdAt: new Date('2025-04-12'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'SCN-003',
    title: 'Ransomware Attack on Critical Infrastructure',
    businessLine: 'Technology',
    product: 'Core Banking System',
    geography: 'United States',
    riskType: 'Cyber',
    inherentRisk: 5,
    controlStrength: 4,
    lossHistory: [
      { amount: 2750000, date: new Date('2025-07-20') },
    ],
    compositeScore: 10,
    narrative:
      'Scenario: Advanced persistent threat (APT) group compromises core banking infrastructure. Ransomware deployed across critical systems. Backup systems also encrypted.',
    probability: 15,
    potentialLoss: 75000000,
    mitigatingControls: ['CTL-021', 'CTL-022', 'CTL-023'],
    owner: 'catherine.davis@bank.com',
    createdAt: new Date('2025-07-01'),
    updatedAt: new Date('2026-02-25'),
  },
];

// ============================================================================
// MONITORING ALERTS - 8+ operational monitoring alerts
// ============================================================================

export const monitoringAlerts: MonitoringAlert[] = [
  {
    id: 'ALT-001',
    type: 'SLA Breach',
    vendorId: 'VND-006',
    severity: 'Medium',
    title: 'Apex Document Management – Response Time SLA Breach',
    description: 'Vendor average response time exceeded 4-hour SLA. Mean time to respond: 5.2 hours for 15% of requests.',
    timestamp: new Date('2026-02-19'),
    acknowledged: true,
    acknowledgedBy: 'james.wilson@bank.com',
    acknowledgedAt: new Date('2026-02-20'),
    aiInterpretation: 'Vendor experiencing capacity constraints. Recommend capacity review or escalation.',
    relatedEntityId: 'VND-006',
    actionRequired: true,
  },
  {
    id: 'ALT-002',
    type: 'Concentration Risk',
    severity: 'High',
    title: 'CRE Portfolio Concentration Exceeds Warning Threshold',
    description: 'CRE concentration ratio breached 20% warning threshold. Current: 24.5% vs threshold 20%.',
    timestamp: new Date('2026-02-20'),
    acknowledged: false,
    aiInterpretation: 'Deteriorating trend over 4 months. Recommend portfolio rebalancing review.',
    relatedEntityId: 'RSK-001',
    actionRequired: true,
  },
  {
    id: 'ALT-003',
    type: 'Cyber Intel',
    severity: 'Medium',
    title: 'Critical Vulnerabilities Detected in Endpoint Infrastructure',
    description: '12 critical-severity vulnerabilities identified in endpoint scanning. Includes potential RCE exploits.',
    timestamp: new Date('2026-02-21'),
    acknowledged: true,
    acknowledgedBy: 'catherine.davis@bank.com',
    acknowledgedAt: new Date('2026-02-21'),
    aiInterpretation: 'Improving trend from 28 critical vulns in Nov 2025. Patch management processes effective.',
    relatedEntityId: 'KRI-011',
    actionRequired: true,
  },
  {
    id: 'ALT-004',
    type: 'Data Incident',
    vendorId: 'VND-002',
    severity: 'High',
    title: 'Unauthorized Data Export Detected – DataVault Analytics',
    description: 'SIEM alert triggered on unusual data extraction patterns from analytics platform. 2.3 GB exported to external IP.',
    timestamp: new Date('2026-02-17'),
    acknowledged: true,
    acknowledgedBy: 'kevin.white@bank.com',
    acknowledgedAt: new Date('2026-02-18'),
    aiInterpretation: 'Investigation ongoing. Data appears to be test/development data. No PII detected. Recommend access control review.',
    relatedEntityId: 'VND-002',
    actionRequired: true,
  },
  {
    id: 'ALT-005',
    type: 'Regulatory Filing',
    severity: 'High',
    title: 'CECL Model Reserve Deficiency Identified',
    description: 'Q4 2025 model validation identified reserve shortfall of $6.75M. Adjustment required for financial statements.',
    timestamp: new Date('2026-01-31'),
    acknowledged: true,
    acknowledgedBy: 'alice.brown@bank.com',
    acknowledgedAt: new Date('2026-02-01'),
    aiInterpretation: 'Macro environment changes warrant model recalibration. Q1 2026 reassessment planned.',
    relatedEntityId: 'LSS-006',
    actionRequired: false,
  },
  {
    id: 'ALT-006',
    type: 'Financial Distress',
    vendorId: 'VND-007',
    severity: 'Medium',
    title: 'TrustBridge KYC – Auditor Going Concern Warning',
    description: 'Vendor financial audit disclosed going concern warning. Credit ratings downgraded to B+ from A-.',
    timestamp: new Date('2026-02-14'),
    acknowledged: true,
    acknowledgedBy: 'lisa.park@bank.com',
    acknowledgedAt: new Date('2026-02-15'),
    aiInterpretation: 'Vendor is key to KYC/AML processes. Consider backup vendor activation timeline. Recommend contract review.',
    relatedEntityId: 'VND-007',
    actionRequired: true,
  },
  {
    id: 'ALT-007',
    type: 'SLA Breach',
    vendorId: 'VND-005',
    severity: 'Critical',
    title: 'PayStream Global – Payment Processing Latency Alert',
    description: 'Payment processing latency exceeded SLA threshold for 45 minutes. 12,500 transactions delayed.',
    timestamp: new Date('2026-02-13'),
    acknowledged: true,
    acknowledgedBy: 'james.wilson@bank.com',
    acknowledgedAt: new Date('2026-02-13'),
    aiInterpretation: 'Root cause: vendor infrastructure upgrade. Graceful degradation observed. Recommend post-incident review meeting.',
    relatedEntityId: 'VND-005',
    actionRequired: false,
  },
  {
    id: 'ALT-008',
    type: 'Concentration Risk',
    severity: 'High',
    title: 'Core Platform Migration – Schedule Variance Exceeds Threshold',
    description: 'Migration project currently 6 months behind original plan. Resource constraints and scope creep cited.',
    timestamp: new Date('2026-02-20'),
    acknowledged: true,
    acknowledgedBy: 'robert.kumar@bank.com',
    acknowledgedAt: new Date('2026-02-20'),
    aiInterpretation: 'Steering committee intervention recommended. Budget impact assessment required.',
    relatedEntityId: 'KRI-008',
    actionRequired: true,
  },
];

// ============================================================================
// AUDIT LOG - Change tracking for compliance
// ============================================================================

export const auditLog: AuditEntry[] = [
  {
    id: 'AUD-001',
    entityType: 'Risk',
    entityId: 'RSK-001',
    action: 'UPDATE',
    field: 'residualScore',
    oldValue: 12,
    newValue: 9,
    user: 'john.chen@bank.com',
    timestamp: new Date('2026-02-15'),
    ipAddress: '192.168.1.100',
  },
  {
    id: 'AUD-002',
    entityType: 'Control',
    entityId: 'CTL-008',
    action: 'UPDATE',
    field: 'testDate',
    oldValue: new Date('2025-11-20'),
    newValue: new Date('2026-02-15'),
    user: 'michael.thompson@bank.com',
    timestamp: new Date('2026-02-15'),
    ipAddress: '192.168.1.101',
  },
  {
    id: 'AUD-003',
    entityType: 'Issue',
    entityId: 'ISS-001',
    action: 'UPDATE',
    field: 'status',
    oldValue: 'Open',
    newValue: 'In Progress',
    user: 'michael.thompson@bank.com',
    timestamp: new Date('2026-02-10'),
    ipAddress: '192.168.1.101',
  },
  {
    id: 'AUD-004',
    entityType: 'KRI',
    entityId: 'KRI-001',
    action: 'UPDATE',
    field: 'currentValue',
    oldValue: 23.5,
    newValue: 24.5,
    user: 'john.chen@bank.com',
    timestamp: new Date('2026-02-20'),
    ipAddress: '192.168.1.100',
  },
  {
    id: 'AUD-005',
    entityType: 'Vendor',
    entityId: 'VND-001',
    action: 'UPDATE',
    field: 'slaStatus',
    oldValue: 'Yellow',
    newValue: 'Green',
    user: 'lisa.park@bank.com',
    timestamp: new Date('2026-02-18'),
    ipAddress: '192.168.1.102',
  },
  {
    id: 'AUD-006',
    entityType: 'LossEvent',
    entityId: 'LSS-001',
    action: 'CREATE',
    user: 'john.chen@bank.com',
    timestamp: new Date('2025-09-15'),
    ipAddress: '192.168.1.100',
  },
  {
    id: 'AUD-007',
    entityType: 'RegulatoryChange',
    entityId: 'REG-006',
    action: 'UPDATE',
    field: 'status',
    oldValue: 'Monitoring',
    newValue: 'Implementation',
    user: 'sarah.martinez@bank.com',
    timestamp: new Date('2026-02-01'),
    ipAddress: '192.168.1.103',
  },
  {
    id: 'AUD-008',
    entityType: 'Issue',
    entityId: 'ISS-004',
    action: 'UPDATE',
    field: 'severity',
    oldValue: 'High',
    newValue: 'Critical',
    user: 'robert.kumar@bank.com',
    timestamp: new Date('2026-02-18'),
    ipAddress: '192.168.1.104',
  },
  {
    id: 'AUD-009',
    entityType: 'Risk',
    entityId: 'RSK-003',
    action: 'UPDATE',
    field: 'status',
    oldValue: 'Active',
    newValue: 'Active',
    user: 'michael.thompson@bank.com',
    timestamp: new Date('2026-02-01'),
    ipAddress: '192.168.1.101',
  },
  {
    id: 'AUD-010',
    entityType: 'Control',
    entityId: 'CTL-010',
    action: 'UPDATE',
    field: 'status',
    oldValue: 'Implemented',
    newValue: 'Under Review',
    user: 'lisa.park@bank.com',
    timestamp: new Date('2025-12-10'),
    ipAddress: '192.168.1.102',
  },
  {
    id: 'AUD-011',
    entityType: 'Issue',
    entityId: 'ISS-002',
    action: 'UPDATE',
    field: 'status',
    oldValue: 'Open',
    newValue: 'Remediation Planned',
    user: 'lisa.park@bank.com',
    timestamp: new Date('2026-02-15'),
    ipAddress: '192.168.1.102',
  },
  {
    id: 'AUD-012',
    entityType: 'KRI',
    entityId: 'KRI-003',
    action: 'UPDATE',
    field: 'currentValue',
    oldValue: 8.8,
    newValue: 8.5,
    user: 'sarah.martinez@bank.com',
    timestamp: new Date('2026-02-21'),
    ipAddress: '192.168.1.103',
  },
  {
    id: 'AUD-013',
    entityType: 'Vendor',
    entityId: 'VND-007',
    action: 'UPDATE',
    field: 'residualRisk',
    oldValue: 2,
    newValue: 3,
    user: 'lisa.park@bank.com',
    timestamp: new Date('2026-02-15'),
    ipAddress: '192.168.1.102',
  },
  {
    id: 'AUD-014',
    entityType: 'MonitoringAlert',
    entityId: 'ALT-002',
    action: 'ACKNOWLEDGE',
    user: 'john.chen@bank.com',
    timestamp: new Date('2026-02-20'),
    ipAddress: '192.168.1.100',
  },
  {
    id: 'AUD-015',
    entityType: 'RiskScenario',
    entityId: 'SCN-003',
    action: 'UPDATE',
    field: 'compositeScore',
    oldValue: 12,
    newValue: 10,
    user: 'catherine.davis@bank.com',
    timestamp: new Date('2026-02-25'),
    ipAddress: '192.168.1.105',
  },
];
